nx = input('Coloque uma letra ou um numero: ')
print('O tipo primitivo é: ',type(nx))
print('é numerico? ', nx.isnumeric())
print('é alfabeto? ', nx.isalpha())
print('tem espaço? ', nx.isspace())
print('é alfanumerico? ', nx.isalnum())
print('tá maiusculo? ', nx.isupper())
print('tá minusculo? ', nx.islower())
print('esta capitalizado? ', nx.istitle())
